
TAGS = {
    1 : ('Sharpness',)
,	2 : ('Number of images',)
,	3 : ('Sensor and ISP gains',)
,	4 : ('Camera using mode',)
,	5 : ('Sensor temperature',)
,	6 : ('High Dynamic Range',)
,	7 : ('High Dynamic Range set',)
,	8 : ('Gravity vector',)
,	9 : ('Detected faces number',)
,	10 : ('Detected faces',)
,	11 : ('Focus mode',)
,	12 : ('Camera controls state',)
,	13 : ('Raw linearization LUT',)
,	14 : ('Advanced gyro information',)
,	15 : ('Image time stamps',)
,	16 : ('Scene mode',)
,	17 : ('Analog gain for ISO 100',)
,	18 : ('TNR JPEG',)
,	19 : ('TNR image IFD index',)
,	20 : ('ISO mode',)
,	21 : ('Format version',)
,	22 : ('Gyro still mean data',)
,	23 : ('Gyro sensitive data',)
,	24 : ('Burst ID',)
,	25 : ('Burst number in sequence',)
,	26 : ('Time-Lapse ID',)
,	27 : ('Time-Lapse number in sequence',)
,	28 : ('Connect processing',)
,	29 : ('Lighting Strength Intensity',)
}
